### ISSUE TITLE
PlatformIO

### ISSUE THREAD

**Issue by nlamirault** [joshglendenning/arduino-nats#5]
Hi, 
i make a new issue [1](https://github.com/platformio/platformio-libmirror/issues/92) to add your library to the PlatformIO environment.

**Comment by ivankravets** [comment]
Hi,

@joshglendenning could you create [library.json](http://docs.platformio.org/en/latest/librarymanager/creating.html) manifest?

Thanks!

**Comment by isobit** [comment]
Oh, sure thing! Should have done this a long time ago, I use (and love) PlatformIO myself, I just usually copy the header manually into my source ¯\_(ツ)_/¯

**Comment by ivankravets** [comment]
Thanks! :)

http://platformio.org/lib/show/1163/ArduinoNATS

**Comment by nlamirault** [comment]
It works. Thanks
