### ISSUE TITLE
Nats and wifi

### ISSUE THREAD

**Issue by nlamirault** [joshglendenning/arduino-nats#6]
Hi,
in your example, there is : 

``` c
#include <ESP8266WiFi.h>
```

Could you find this library in PlatformIO ?
Thanks

**Comment by isobit** [comment]
This is part of the ESP8266 Arduino library, it will be available if you are using the Arduino framework.

See https://github.com/esp8266/Arduino/blob/master/doc/esp8266wifi/readme.md#quick-start.

**Comment by isobit** [comment]
I believe if you are using an Atmel Arduino, the equivalent is 

``` arduino
#include <WiFi.h>
```

https://www.arduino.cc/en/Tutorial/WiFiWebClient
