### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by ben-barnes** [joshglendenning/arduino-nats#7]
One of my team is looking into adding NATS streaming support, and would like to share his changes (if you're interested). Our open source release process makes it difficult to contribute to projects without a license. Would you be willing to add one?

**Comment by isobit** [comment]
Oh, absolutely. I can't believe I forgot to add one!

I am working on replacing dynamic memory allocation with static buffers and some other improvements, I'll get that up in a branch when I get the chance since it might affect your team member's changes.

**Comment by isobit** [comment]
https://github.com/joshglendenning/arduino-nats/commit/fe1ad272c8ec086da97741f7a1fa3ee034654219

**Comment by ben-barnes** [comment]
Thanks for that!
